TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += Lakeshore340.db
DATA += Lakeshore340.proto

#=======================================
include $(TOP)/configure/RULES
